DISABLE_STONE_SPEAR = false
DISABLE_STEEL_SPEAR = true
DISABLE_COPPER_SPEAR = false
DISABLE_BRONZE_SPEAR = true
DISABLE_DIAMOND_SPEAR = false
DISABLE_OBSIDIAN_SPEAR = false
DISABLE_GOLD_SPEAR = false
DISABLE_IRON_SPEAR = false
SPEARS_THROW_SPEED = 13
SPEARS_V_ZERO = {x = 0, y = 0, z = 0}
SPEARS_DRAG_COEFF = 0.1
SPEARS_NODE_UNKNOWN = nil
SPEARS_NODE_THROUGH = 0
SPEARS_NODE_STICKY = 1
SPEARS_NODE_CRACKY = 2
SPEARS_NODE_CRACKY_LIMIT = 3
